server:
  port: 40100
spring:
  application:
    name: xc-service-search
xuecheng:
  elasticsearch:
    hostlist: ${ES_HOSTLIST:127.0.0.1:9200}    #多个结点中间用逗号分隔
    course:
      index: xc_course
      type: doc
      fields: id,name
    media:
      index: xc_course_media
      type: doc