server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
#  main:
#    allow-circular-references: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8&useSSL=false
      username: root
      password: hl950510XN
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:
    mongodb:
      database: xc_cms
page helper:
  helper-dialect: mysql

# 课程发布参数
course-publish:
  siteId: 646dac8b0acf03164373dba4      # 课程详情站点
  templateId: 6465e7d39427c37b1ae83258
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31200/course/courseview/
  previewUrlPre: http://www.xuecheng.test/cms/preview/