server:
  port: 50201

spring:
  application:
    name: xc-govern-gateway
  main:
    web-application-type: reactive
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  cloud:
    gateway:
      routes:
        - id: xc-service-manage-cms
          uri: lb://xc-service-manage-cms
          predicates:
            - Path=/api/cms/**
          filters:
            - StripPrefix=1
